### ISSUE TITLE
file vocab/vocab_chars.json not available

### ISSUE THREAD

**Issue by molden** [thomas0809/MolScribe#1]
First of all, thanks for this great contribution to the field. I wanted to test some part of the code but bumped into this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'vocab/vocab_chars.json'` . Would it be possible to make this file available? Thanks.

**Comment by thomas0809** [comment]
Thanks for bringing this to my attention. The vocab file is available: https://github.com/thomas0809/MolScribe/blob/main/molscribe/vocab/vocab_chars.json

Could you please let me know which command you used to run the code? I noticed the vocab path in my bash scripts are wrong and just updated them. The prediction API is not affected by this and should work.

**Comment by molden** [comment]
Thanks, I was trying:
`bash scripts/train_uspto_joint_chartok.sh `
it now indeed found the file in the right place thanks to your commit 9b26633e1b679f8964840aa4f169079b2be659b7 .
