### ISSUE TITLE
How to convert Raw_SMILES to SMILES

### ISSUE THREAD

**Issue by freewind2213** [thomas0809/MolScribe#11]
Hi, I'm trying to figure out how the USPTO data annotation file is generated. Given the Raw SMILES and mol file, how can I convert Raw_SMILES into SMILES column in the label file named train_680k.csv.

Thx!!!

**Comment by thomas0809** [comment]
Please see #2

**Comment by freewind2213** [comment]
Got it , excellent work!!!
