### ISSUE TITLE
当一个batch中，推理两条完全一样的图片，产生的结果不一致。

### ISSUE THREAD

**Issue by DaXia-Yang** [thomas0809/MolScribe#21]
![image](https://github.com/thomas0809/MolScribe/assets/55680227/84600d6c-4127-49fa-a127-b95d7d8b8f9f)

When inferring two identical data in a batch, different inference results will be generated. I identified the reason as the code in the red box causing the problem: the addition of x at the same position with different Positional Encoding resulted in inconsistent calculation results.

**Comment by DaXia-Yang** [comment]
Should be changed to：emb = emb + self.pe[step]
Because the dimension of emb is 'b*1*dim'

**Comment by thomas0809** [comment]
Hi,

Thanks for raising this issue! I haven't checked it carefully, but you are probably correct. (It would be great if you could confirm that the `emb.shape` here is (batch_size, seq_len, dim). Then it means I didn't use this class correctly - see the doc string.)

If it is true, I guess the reason why the model is still working is that during training, the examples in a batch also get different positional encoding, i.e., the 0th one starts with 0, the 1st one starts with 1. But it is definitely a bug. Retraining the model after fixing this bug can probably improve the model.
