### ISSUE TITLE
bond angle(?) issue

### ISSUE THREAD

**Issue by sistar2020** [thomas0809/MolScribe#31]
The following two images are seemingly almost identical:
&nbsp;
Image1:
<img width="177" alt="image-1" src="https://github.com/user-attachments/assets/28c97cb7-df47-45bc-8188-57186f62c6dd">
Image2:
<img width="177" alt="image-2" src="https://github.com/user-attachments/assets/03d2c1d9-39c8-4288-889f-2b3785f17958">
&nbsp;
Image1 gives a correct SMILES, but Image2 gives a wrong one.
```
Image1: Cn1c(=O)c(=O)n(C)c2cc(S(=O)(=O)N3CCC4(CC3)Nc3ccccc3-n3cccc34)ccc21
Image2: Cn1c(=O)c(=O)n(C)c2cc([S@TB13](=O)(=O)N3CCC4(CC3)Nc3ccccc3-n3cccc34)ccc21
```

I thought this is a bit weird since there are no elements like T and B in Image2.

**Comment by LingjieBao1998** [comment]
This is special chirality in `rdkit` for S or P and other multi-electron compound, you can refer to the <a src="https://www.rdkit.org/docs/RDKit_Book.html">link</a>.
![image](https://github.com/user-attachments/assets/ee2e41cb-b61e-4654-99ce-2e11bb046b10)
`
for atom in mol.GetAtoms():
    if atom.GetSymbol() != "C":
        atom.SetChiralTag(Chem.rdchem.ChiralType.CHI_UNSPECIFIED)
`

**Comment by sistar2020** [comment]
Gotcha!
Thank you very much.
