### ISSUE TITLE
Images that do not contain chemical structures are less effective

### ISSUE THREAD

**Issue by echo0218** [thomas0809/MolScribe#4]
![Table_2](https://github.com/thomas0809/MolScribe/assets/11382853/0287b828-c90e-4ce6-8fb4-142007bc336c)
![PicID_15](https://github.com/thomas0809/MolScribe/assets/11382853/6a2518b4-7445-444e-ab11-993728d87622)
For these two images, which do not contain chemical structures, MolScribe was able to extract SMILES data with confidence greater than 0.6.  How can solve this problem??

**Comment by thomas0809** [comment]
Great question! In our current training procedure, we did not include images that do not contain molecule structures. Thus, the model always predicts a SMILES string for any image.

I believe this problem can be addressed by adding such training data, i.e., non-molecule images.
