### ISSUE TITLE
cannot import name 'safe_rotate_enlarged_img_size' from 'albumentations.augmentations.geometric.functional'

### ISSUE THREAD

**Issue by qbKhanh** [thomas0809/MolScribe#6]
When i try to run the following cell code,
`from molscribe import MolScribe

device = torch.device('cpu')
model = MolScribe(MODEL_PATH, device)
prediction = model.predict_image_file(IMAGE_PATH, return_atoms_bonds=True)
smiles = prediction['smiles']
molfile = prediction['molfile']`

I found that import error: ImportError: cannot import name 'safe_rotate_enlarged_img_size' from 'albumentations.augmentations.geometric.functional'

Hope you reply me soon!

**Comment by thomas0809** [comment]
Hi,

Please use albumentations v1.1.0, as specified in [setup.py](https://github.com/thomas0809/MolScribe/blob/main/setup.py).

Specifically, you could do `pip install albumentations==1.1.0`.

Hope it helps!

**Comment by qbKhanh** [comment]
Sh i can fixed it. Thank for your hard-working!

**Comment by qbKhanh** [comment]
Can I ask you an additional question?

**Comment by thomas0809** [comment]
> Can I ask you an additional question?

Sure, what is your question?

**Comment by qbKhanh** [comment]
I raised in another issue. You can reply on it.
Thank you very much!
