### ISSUE TITLE
感谢你开源的MolScribe模型，已经试用了，准确性还不错。想请教一下，关于分子位置检测有推荐的开源模型吗？

### ISSUE THREAD

**Issue by SnailWhb** [thomas0809/MolScribe#9]

**Comment by LingjieBao1998** [comment]
刚好最近也在follow这些工作，这篇工作不错(https://github.com/Kohulan/DECIMER-Image-Segmentation.git)，不过召回率的话不是100%。当然还是很感谢MolScribe模型的开源工作。

**Comment by SnailWhb** [comment]
> 刚好最近也在follow这些工作，这篇工作不错（[https://github.com/Kohulan/DECIMER-Image-Segmentation](https://github.com/Kohulan/DECIMER-Image-Segmentation.git)），不过召回率的话不是100%。当然还是很感谢MolScribe模型的开源工作。

谢谢回复，DECIMER-IMAGE-Segmentation召回率有待提高，它是基于Mask-RCNN训练的，想要基于Transformer框架重新训练一个分子检测模型，但无奈没有找到相关的公开数据集.

**Comment by LingjieBao1998** [comment]
> > 刚好最近也在follow这些工作，这篇工作不错（[https://github.com/Kohulan/DECIMER-Image-Segmentation](https://github.com/Kohulan/DECIMER-Image-Segmentation.git)），不过召回率的话不是100%。当然还是很感谢MolScribe模型的开源工作。
> 
> 谢谢回复，DECIMER-IMAGE-Segmentation召回率有待提高，它是基于Mask-RCNN训练的，想要基于Transformer框架重新训练一个分子检测模型，但无奈没有找到相关的公开数据集.

是的，他们没有提供数据集，但是原始文献中文章中提供了数据标注的方式。

**Comment by thomas0809** [comment]
谢谢你对我们工作的兴趣！

我们有一个Transformer-based molecule detection model，最近（可能一两周）就会公开，我过几天在这里更新。

**Comment by thomas0809** [comment]
Hi,

I would like to introduce you to a new tool we have developed: https://github.com/Ozymandias314/MolDetect. It is a Transformer-based molecule detection model. We will be releasing our manuscript soon. Please stay tuned.

**Comment by LingjieBao1998** [comment]
> Hi,
> 
> I would like to introduce you to a new tool we have developed: https://github.com/Ozymandias314/MolDetect. It is a Transformer-based molecule detection model. We will be releasing our manuscript soon. Please stay tuned.↳

Thanks for your hard work.

**Comment by SnailWhb** [comment]
> Hi,
> 
> I would like to introduce you to a new tool we have developed: https://github.com/Ozymandias314/MolDetect. It is a Transformer-based molecule detection model. We will be releasing our manuscript soon. Please stay tuned.

非常感谢，已测试。整体效果相对[DECIMER-Image-Segmentation](https://github.com/Kohulan/DECIMER-Image-Segmentation.git)要好一些，但对于分子之间很小时，出错的概率较大。
![image](https://github.com/thomas0809/MolScribe/assets/26184928/f6b9f1dd-8cbd-4d48-a3dc-4863cd6b086f)

![image](https://github.com/thomas0809/MolScribe/assets/26184928/a0133549-3bb4-4ad4-8368-9517bad18f13)
